import { createFileRoute } from "@tanstack/react-router";
import { StatusBadge } from "@/components/StatusBadge";
import { pendencies, vehicles, services } from "@/lib/mock-data";
import { formatDate, num } from "@/lib/calculations";
import { pendencySeverityLabel, pendencySeverityTone, serviceCategoryLabel } from "@/lib/status-rules";
import type { PendencySeverity } from "@/types/fleet";

export const Route = createFileRoute("/mechanic/pendencias")({ head: () => ({ meta: [{ title: "Mecânico — Pendências" }] }), component: MechanicPendencies });
const groups: { key: PendencySeverity; title: string }[] = [{ key: "critica", title: "Críticas" }, { key: "atencao", title: "Atenção" }, { key: "baixa", title: "Baixa" }];
function MechanicPendencies() {
  const open = pendencies.filter((p) => p.status === "aberta");
  return <div className="mx-auto max-w-md space-y-4 p-4"><header><div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Pendências</div><h1 className="text-xl font-semibold">Fila de manutenção</h1><p className="text-sm text-muted-foreground">{open.length} itens em aberto para revisar ou executar.</p></header>{groups.map((g) => { const list = open.filter((p) => p.severity === g.key); return <section key={g.key} className="rounded-xl border border-border bg-card"><div className="border-b border-border px-3 py-2"><h2 className="text-sm font-semibold">{g.title} ({list.length})</h2></div><div className="divide-y divide-border">{list.length === 0 && <div className="p-4 text-sm text-muted-foreground">Nenhum item.</div>}{list.map((p) => { const v = vehicles.find((x) => x.id === p.vehicleId); const s = services.find((x) => x.id === p.serviceId); return <a key={p.id} href={v ? `/mechanic/veiculos/${v.id}` : "#"} className="block p-3 hover:bg-muted/40"><div className="flex items-start justify-between gap-2"><div><div className="text-sm font-semibold">{p.title}</div><p className="text-xs text-muted-foreground">{p.description}</p></div><StatusBadge tone={pendencySeverityTone[p.severity]}>{pendencySeverityLabel[p.severity]}</StatusBadge></div><div className="mt-2 flex flex-wrap gap-2 text-[11px] text-muted-foreground">{v && <span>{v.plate} · {v.model}</span>}{s && <span>{serviceCategoryLabel[s.category]} · {s.name}</span>}{p.currentKm && <span>Atual {num(p.currentKm)} km</span>}{p.dueKm && <span>Limite {num(p.dueKm)} km</span>}{p.dueDate && <span>Prazo {formatDate(p.dueDate)}</span>}</div><button className="mt-3 w-full rounded-lg bg-primary py-2 text-xs font-semibold text-primary-foreground">{p.actionLabel}</button></a>; })}</div></section>; })}</div>;
}
