/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MechanicRouteImport } from './routes/mechanic'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MechanicIndexRouteImport } from './routes/mechanic.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MechanicVeiculosRouteImport } from './routes/mechanic.veiculos'
import { Route as MechanicServicosRouteImport } from './routes/mechanic.servicos'
import { Route as MechanicPendenciasRouteImport } from './routes/mechanic.pendencias'
import { Route as AdminViagensRouteImport } from './routes/admin.viagens'
import { Route as AdminVeiculosRouteImport } from './routes/admin.veiculos'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminPendenciasRouteImport } from './routes/admin.pendencias'
import { Route as AdminMotoristasRouteImport } from './routes/admin.motoristas'
import { Route as AdminMecanicosRouteImport } from './routes/admin.mecanicos'
import { Route as AdminManutencoesRouteImport } from './routes/admin.manutencoes'
import { Route as AdminDespesasRouteImport } from './routes/admin.despesas'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAbastecimentosRouteImport } from './routes/admin.abastecimentos'
import { Route as MechanicVeiculosIdRouteImport } from './routes/mechanic.veiculos.$id'
import { Route as AdminViagensIdRouteImport } from './routes/admin.viagens.$id'
import { Route as AdminVeiculosIdRouteImport } from './routes/admin.veiculos.$id'
import { Route as AdminMotoristasIdRouteImport } from './routes/admin.motoristas.$id'
import { Route as AdminManutencoesIdRouteImport } from './routes/admin.manutencoes.$id'

const MechanicRoute = MechanicRouteImport.update({
  id: '/mechanic',
  path: '/mechanic',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicIndexRoute = MechanicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MechanicRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MechanicVeiculosRoute = MechanicVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicServicosRoute = MechanicServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicPendenciasRoute = MechanicPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => MechanicRoute,
} as any)
const AdminViagensRoute = AdminViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendenciasRoute = AdminPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMotoristasRoute = AdminMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMecanicosRoute = AdminMecanicosRouteImport.update({
  id: '/mecanicos',
  path: '/mecanicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManutencoesRoute = AdminManutencoesRouteImport.update({
  id: '/manutencoes',
  path: '/manutencoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDespesasRoute = AdminDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbastecimentosRoute = AdminAbastecimentosRouteImport.update({
  id: '/abastecimentos',
  path: '/abastecimentos',
  getParentRoute: () => AdminRoute,
} as any)
const MechanicVeiculosIdRoute = MechanicVeiculosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MechanicVeiculosRoute,
} as any)
const AdminViagensIdRoute = AdminViagensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminViagensRoute,
} as any)
const AdminVeiculosIdRoute = AdminVeiculosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVeiculosRoute,
} as any)
const AdminMotoristasIdRoute = AdminMotoristasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMotoristasRoute,
} as any)
const AdminManutencoesIdRoute = AdminManutencoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminManutencoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/mechanic': typeof MechanicRouteWithChildren
  '/admin/abastecimentos': typeof AdminAbastecimentosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/despesas': typeof AdminDespesasRoute
  '/admin/manutencoes': typeof AdminManutencoesRouteWithChildren
  '/admin/mecanicos': typeof AdminMecanicosRoute
  '/admin/motoristas': typeof AdminMotoristasRouteWithChildren
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/veiculos': typeof AdminVeiculosRouteWithChildren
  '/admin/viagens': typeof AdminViagensRouteWithChildren
  '/mechanic/pendencias': typeof MechanicPendenciasRoute
  '/mechanic/servicos': typeof MechanicServicosRoute
  '/mechanic/veiculos': typeof MechanicVeiculosRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/mechanic/': typeof MechanicIndexRoute
  '/admin/manutencoes/$id': typeof AdminManutencoesIdRoute
  '/admin/motoristas/$id': typeof AdminMotoristasIdRoute
  '/admin/veiculos/$id': typeof AdminVeiculosIdRoute
  '/admin/viagens/$id': typeof AdminViagensIdRoute
  '/mechanic/veiculos/$id': typeof MechanicVeiculosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/abastecimentos': typeof AdminAbastecimentosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/despesas': typeof AdminDespesasRoute
  '/admin/manutencoes': typeof AdminManutencoesRouteWithChildren
  '/admin/mecanicos': typeof AdminMecanicosRoute
  '/admin/motoristas': typeof AdminMotoristasRouteWithChildren
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/veiculos': typeof AdminVeiculosRouteWithChildren
  '/admin/viagens': typeof AdminViagensRouteWithChildren
  '/mechanic/pendencias': typeof MechanicPendenciasRoute
  '/mechanic/servicos': typeof MechanicServicosRoute
  '/mechanic/veiculos': typeof MechanicVeiculosRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/mechanic': typeof MechanicIndexRoute
  '/admin/manutencoes/$id': typeof AdminManutencoesIdRoute
  '/admin/motoristas/$id': typeof AdminMotoristasIdRoute
  '/admin/veiculos/$id': typeof AdminVeiculosIdRoute
  '/admin/viagens/$id': typeof AdminViagensIdRoute
  '/mechanic/veiculos/$id': typeof MechanicVeiculosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/mechanic': typeof MechanicRouteWithChildren
  '/admin/abastecimentos': typeof AdminAbastecimentosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/despesas': typeof AdminDespesasRoute
  '/admin/manutencoes': typeof AdminManutencoesRouteWithChildren
  '/admin/mecanicos': typeof AdminMecanicosRoute
  '/admin/motoristas': typeof AdminMotoristasRouteWithChildren
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/veiculos': typeof AdminVeiculosRouteWithChildren
  '/admin/viagens': typeof AdminViagensRouteWithChildren
  '/mechanic/pendencias': typeof MechanicPendenciasRoute
  '/mechanic/servicos': typeof MechanicServicosRoute
  '/mechanic/veiculos': typeof MechanicVeiculosRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/mechanic/': typeof MechanicIndexRoute
  '/admin/manutencoes/$id': typeof AdminManutencoesIdRoute
  '/admin/motoristas/$id': typeof AdminMotoristasIdRoute
  '/admin/veiculos/$id': typeof AdminVeiculosIdRoute
  '/admin/viagens/$id': typeof AdminViagensIdRoute
  '/mechanic/veiculos/$id': typeof MechanicVeiculosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/mechanic'
    | '/admin/abastecimentos'
    | '/admin/dashboard'
    | '/admin/despesas'
    | '/admin/manutencoes'
    | '/admin/mecanicos'
    | '/admin/motoristas'
    | '/admin/pendencias'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/veiculos'
    | '/admin/viagens'
    | '/mechanic/pendencias'
    | '/mechanic/servicos'
    | '/mechanic/veiculos'
    | '/admin/'
    | '/driver/'
    | '/mechanic/'
    | '/admin/manutencoes/$id'
    | '/admin/motoristas/$id'
    | '/admin/veiculos/$id'
    | '/admin/viagens/$id'
    | '/mechanic/veiculos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/abastecimentos'
    | '/admin/dashboard'
    | '/admin/despesas'
    | '/admin/manutencoes'
    | '/admin/mecanicos'
    | '/admin/motoristas'
    | '/admin/pendencias'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/veiculos'
    | '/admin/viagens'
    | '/mechanic/pendencias'
    | '/mechanic/servicos'
    | '/mechanic/veiculos'
    | '/admin'
    | '/driver'
    | '/mechanic'
    | '/admin/manutencoes/$id'
    | '/admin/motoristas/$id'
    | '/admin/veiculos/$id'
    | '/admin/viagens/$id'
    | '/mechanic/veiculos/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/mechanic'
    | '/admin/abastecimentos'
    | '/admin/dashboard'
    | '/admin/despesas'
    | '/admin/manutencoes'
    | '/admin/mecanicos'
    | '/admin/motoristas'
    | '/admin/pendencias'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/veiculos'
    | '/admin/viagens'
    | '/mechanic/pendencias'
    | '/mechanic/servicos'
    | '/mechanic/veiculos'
    | '/admin/'
    | '/driver/'
    | '/mechanic/'
    | '/admin/manutencoes/$id'
    | '/admin/motoristas/$id'
    | '/admin/veiculos/$id'
    | '/admin/viagens/$id'
    | '/mechanic/veiculos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  MechanicRoute: typeof MechanicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mechanic': {
      id: '/mechanic'
      path: '/mechanic'
      fullPath: '/mechanic'
      preLoaderRoute: typeof MechanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanic/': {
      id: '/mechanic/'
      path: '/'
      fullPath: '/mechanic/'
      preLoaderRoute: typeof MechanicIndexRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mechanic/veiculos': {
      id: '/mechanic/veiculos'
      path: '/veiculos'
      fullPath: '/mechanic/veiculos'
      preLoaderRoute: typeof MechanicVeiculosRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/servicos': {
      id: '/mechanic/servicos'
      path: '/servicos'
      fullPath: '/mechanic/servicos'
      preLoaderRoute: typeof MechanicServicosRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/pendencias': {
      id: '/mechanic/pendencias'
      path: '/pendencias'
      fullPath: '/mechanic/pendencias'
      preLoaderRoute: typeof MechanicPendenciasRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/admin/viagens': {
      id: '/admin/viagens'
      path: '/viagens'
      fullPath: '/admin/viagens'
      preLoaderRoute: typeof AdminViagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pendencias': {
      id: '/admin/pendencias'
      path: '/pendencias'
      fullPath: '/admin/pendencias'
      preLoaderRoute: typeof AdminPendenciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/motoristas': {
      id: '/admin/motoristas'
      path: '/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AdminMotoristasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mecanicos': {
      id: '/admin/mecanicos'
      path: '/mecanicos'
      fullPath: '/admin/mecanicos'
      preLoaderRoute: typeof AdminMecanicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manutencoes': {
      id: '/admin/manutencoes'
      path: '/manutencoes'
      fullPath: '/admin/manutencoes'
      preLoaderRoute: typeof AdminManutencoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/despesas': {
      id: '/admin/despesas'
      path: '/despesas'
      fullPath: '/admin/despesas'
      preLoaderRoute: typeof AdminDespesasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abastecimentos': {
      id: '/admin/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/admin/abastecimentos'
      preLoaderRoute: typeof AdminAbastecimentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mechanic/veiculos/$id': {
      id: '/mechanic/veiculos/$id'
      path: '/$id'
      fullPath: '/mechanic/veiculos/$id'
      preLoaderRoute: typeof MechanicVeiculosIdRouteImport
      parentRoute: typeof MechanicVeiculosRoute
    }
    '/admin/viagens/$id': {
      id: '/admin/viagens/$id'
      path: '/$id'
      fullPath: '/admin/viagens/$id'
      preLoaderRoute: typeof AdminViagensIdRouteImport
      parentRoute: typeof AdminViagensRoute
    }
    '/admin/veiculos/$id': {
      id: '/admin/veiculos/$id'
      path: '/$id'
      fullPath: '/admin/veiculos/$id'
      preLoaderRoute: typeof AdminVeiculosIdRouteImport
      parentRoute: typeof AdminVeiculosRoute
    }
    '/admin/motoristas/$id': {
      id: '/admin/motoristas/$id'
      path: '/$id'
      fullPath: '/admin/motoristas/$id'
      preLoaderRoute: typeof AdminMotoristasIdRouteImport
      parentRoute: typeof AdminMotoristasRoute
    }
    '/admin/manutencoes/$id': {
      id: '/admin/manutencoes/$id'
      path: '/$id'
      fullPath: '/admin/manutencoes/$id'
      preLoaderRoute: typeof AdminManutencoesIdRouteImport
      parentRoute: typeof AdminManutencoesRoute
    }
  }
}

interface AdminManutencoesRouteChildren {
  AdminManutencoesIdRoute: typeof AdminManutencoesIdRoute
}

const AdminManutencoesRouteChildren: AdminManutencoesRouteChildren = {
  AdminManutencoesIdRoute: AdminManutencoesIdRoute,
}

const AdminManutencoesRouteWithChildren =
  AdminManutencoesRoute._addFileChildren(AdminManutencoesRouteChildren)

interface AdminMotoristasRouteChildren {
  AdminMotoristasIdRoute: typeof AdminMotoristasIdRoute
}

const AdminMotoristasRouteChildren: AdminMotoristasRouteChildren = {
  AdminMotoristasIdRoute: AdminMotoristasIdRoute,
}

const AdminMotoristasRouteWithChildren = AdminMotoristasRoute._addFileChildren(
  AdminMotoristasRouteChildren,
)

interface AdminVeiculosRouteChildren {
  AdminVeiculosIdRoute: typeof AdminVeiculosIdRoute
}

const AdminVeiculosRouteChildren: AdminVeiculosRouteChildren = {
  AdminVeiculosIdRoute: AdminVeiculosIdRoute,
}

const AdminVeiculosRouteWithChildren = AdminVeiculosRoute._addFileChildren(
  AdminVeiculosRouteChildren,
)

interface AdminViagensRouteChildren {
  AdminViagensIdRoute: typeof AdminViagensIdRoute
}

const AdminViagensRouteChildren: AdminViagensRouteChildren = {
  AdminViagensIdRoute: AdminViagensIdRoute,
}

const AdminViagensRouteWithChildren = AdminViagensRoute._addFileChildren(
  AdminViagensRouteChildren,
)

interface AdminRouteChildren {
  AdminAbastecimentosRoute: typeof AdminAbastecimentosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDespesasRoute: typeof AdminDespesasRoute
  AdminManutencoesRoute: typeof AdminManutencoesRouteWithChildren
  AdminMecanicosRoute: typeof AdminMecanicosRoute
  AdminMotoristasRoute: typeof AdminMotoristasRouteWithChildren
  AdminPendenciasRoute: typeof AdminPendenciasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminVeiculosRoute: typeof AdminVeiculosRouteWithChildren
  AdminViagensRoute: typeof AdminViagensRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbastecimentosRoute: AdminAbastecimentosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDespesasRoute: AdminDespesasRoute,
  AdminManutencoesRoute: AdminManutencoesRouteWithChildren,
  AdminMecanicosRoute: AdminMecanicosRoute,
  AdminMotoristasRoute: AdminMotoristasRouteWithChildren,
  AdminPendenciasRoute: AdminPendenciasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminVeiculosRoute: AdminVeiculosRouteWithChildren,
  AdminViagensRoute: AdminViagensRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverRouteChildren {
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface MechanicVeiculosRouteChildren {
  MechanicVeiculosIdRoute: typeof MechanicVeiculosIdRoute
}

const MechanicVeiculosRouteChildren: MechanicVeiculosRouteChildren = {
  MechanicVeiculosIdRoute: MechanicVeiculosIdRoute,
}

const MechanicVeiculosRouteWithChildren =
  MechanicVeiculosRoute._addFileChildren(MechanicVeiculosRouteChildren)

interface MechanicRouteChildren {
  MechanicPendenciasRoute: typeof MechanicPendenciasRoute
  MechanicServicosRoute: typeof MechanicServicosRoute
  MechanicVeiculosRoute: typeof MechanicVeiculosRouteWithChildren
  MechanicIndexRoute: typeof MechanicIndexRoute
}

const MechanicRouteChildren: MechanicRouteChildren = {
  MechanicPendenciasRoute: MechanicPendenciasRoute,
  MechanicServicosRoute: MechanicServicosRoute,
  MechanicVeiculosRoute: MechanicVeiculosRouteWithChildren,
  MechanicIndexRoute: MechanicIndexRoute,
}

const MechanicRouteWithChildren = MechanicRoute._addFileChildren(
  MechanicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  MechanicRoute: MechanicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
